# -----------------------------------
# Configurações para o banco de dados
spring.datasource.url=jdbc:mysql://localhost:3306/vollmed_api
spring.datasource.username=root
spring.datasource.password=root

# -----------------------------------
# Essa configuração irá ajudar o Spring a encontrar o driver do MySQL
spring.datasource.driver-class-name=com.mysql.jdbc.Driver