services:
  postgres:
    image: postgres
    container_name: petland-api
    environment:
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: petland-api
    ports:
      - 5432:5432
    restart: always
